Persian language PR conflicts resolve #216
lydiahallie/javascript-questions pull request #260
Opened 2019-10-13 08:02 UTC by contributorpw

2019-10-13 08:03 UTC, contributorpw commented
@lydiahallie this PR automatically closes #216 too.

2020-09-06 16:11 UTC, jakeherp commented on fa-IR/README-fa_IR.md
> +Variables with the `let` keyword (and `const`) are hoisted, but unlike `var`, don't get <i>initialized</i>. They are not accessible before the line we declare (initialize) them. This is called the "t
All the explanations are still in English, these will need to be translated before this PR can be merged.

2020-09-06 16:11 UTC, jakeherp requested changes
All the explanations are still in English, these will need to be translated before this PR can be merged.

2020-10-05 10:48 UTC, jakeherp commented
Closing due to inactivity

2020-10-05 10:48 UTC, closed without merging