Add polish version of the questions
lydiahallie/javascript-questions pull request #276
Opened 2019-11-22 15:26 UTC by Shoulao

Hey @lydiahallie!

Here you have the questions 1-124 in polish! Today I will add more. You can merge :)

2020-01-15 16:30 UTC, lydiahallie commented
Thanks so much! Could you maybe provide a link to the polish translation in the original English readmes?

2020-01-15 16:51 UTC, Shoulao commented
> Thanks so much! Could you maybe provide a link to the polish translation in the original English readmes?

Done

2020-01-15 17:31 UTC, lydiahallie commented on README.md
> +* [Polish](../pl-PL/README-pl_PL.md)
```suggestion
* [Polish](./pl-PL/README-pl_PL.md)
```

2020-01-15 17:54 UTC, Shoulao commented
My bad, I was doing this in a hurry

2020-09-06 16:18 UTC, jakeherp requested changes
See below:

2020-09-06 16:18 UTC, jakeherp commented on pl-PL/README-pl_PL.md
> +###### TBC ----------->
If all following questions were not translated yet, can you remove them for now to avoid confusion?

2020-10-05 10:48 UTC, jakeherp commented
Closing due to inactivity.

2020-10-05 10:48 UTC, closed without merging