Menambah yang belum di terjemah
lydiahallie/javascript-questions pull request #443
Opened 2020-10-01 13:26 UTC by Munawir712

2020-10-01 13:58 UTC, tryoasnafi requested changes
This is just translates the question, can you please also translate the solution text for those you update?

2020-10-01 14:04 UTC, Munawir712 commented
> This is just translates the question, can you please also translate the solution text for those you update?

okay soon

2020-10-01 14:23 UTC, jakeherp requested changes
Please translate full questions, not just the titles.

2020-10-02 07:19 UTC, jakeherp approved these changes

2020-10-02 07:19 UTC, merged