enchanment and adding translations for 71, 107,108, and 141
lydiahallie/javascript-questions pull request #458
Opened 2020-10-02 03:50 UTC by SamX23

Enchanment:

- Answer no. 2

Adding Translations:
- Question no. 71
- Answer and question no. 107
- Answer and question no. 108
- Answer no. 141

2020-10-02 07:27 UTC, jakeherp requested changes
Please resolve merge conflicts.

2020-10-02 09:12 UTC, jakeherp commented
@SamX23 I still see merge conflicts here.

2020-10-02 09:40 UTC, SamX23 commented
Hi @jakeherp , im sorry, now i have merged and solved it, please review if you have time. Thank you.

2020-10-02 09:46 UTC, jakeherp commented on id-ID/README.md
> +!"Lydia";
You have changed these from single to double quotes, is there a reason for this?

2020-10-02 09:54 UTC, SamX23 commented on id-ID/README.md
> +!"Lydia";
I'm using vscode prettier plugins, must be changed automatically. Do I need to revert it ?

2020-10-02 12:25 UTC, jakeherp commented on id-ID/README.md
> +!"Lydia";
Yes, please!

2020-10-02 13:54 UTC, SamX23 commented on id-ID/README.md
> +!"Lydia";
Hi, I have reverted it, and only show my translations now. Please take a look at it :)

2020-10-05 07:13 UTC, jakeherp requested changes
Everything before question 152 is now changed back from Indonesian to English, can you please undo this?

2020-10-05 07:53 UTC, SamX23 commented
Sorry, let me fix this

2020-10-05 10:52 UTC, SamX23 commented
Hi, I have fixed the translation and has been update from lydiahallie/master, please have a look at it. :)

2020-10-05 10:59 UTC, jakeherp requested changes
These still need to be resolved.

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +- D: `NaN` and `63`
Still English

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +- C: `false` and `false`
Still English

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +###### 5. Which one is true?
Still English

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +When you change one object, you change all of them.
Still English

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +###### 10. What happens when we do this?
Still English

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +You can't add properties to a constructor like you can with regular objects. If you want to add a feature to all objects at once, you have to use the prototype instead. So in this case,
Still English

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +would have made `member.getFullName()` work. Why is this beneficial? Say that we added this method to the constructor itself. Maybe not every `Person` instance needed this method. This would waste a
Still English

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +- D:`Person {firstName: "Lydia", lastName: "Hallie"}` and `ReferenceError`
Still English

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +###### 14. All object have prototypes.
Still English

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +};
Formatting incorrect

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +const promise4 = Promise.resolve("Fourth");
Formatting incorrect

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +};
Formatting incorrect

2020-10-05 10:59 UTC, jakeherp commented on id-ID/README.md
> +  .catch((err) => console.log(err));
Formatting incorrect

2020-10-05 11:17 UTC, SamX23 commented
Hi, thank you for your review, I have made some changes, including the tab indentation as you mentioned before. :)

2020-10-05 12:48 UTC, jakeherp approved these changes

2020-10-05 12:48 UTC, merged

2020-10-05 13:14 UTC, SamX23 commented
Thank you so much, I've learned a lot :)