✏️ Fix typo in q12 answer
lydiahallie/javascript-questions pull request #558
Opened 2021-04-23 06:28 UTC by hubiwibe

There is a typo in the answer to question 12.

Wrong: 이<ins>~~리~~</ins>고 말했었어요. (그렇지만) 우리<ins>~~는~~</ins> 실제로 한 일은

Right: 이<ins>**라**</ins>고 말했었어요. (그렇지만) 우리<ins>**가**</ins> 실제로 한 일은

2021-04-28 21:09 UTC, jakeherp requested changes
Thanks for your contribution! Can you please revert the formatting changes and only change the typo, so we can merge it?

2021-04-29 00:45 UTC, hubiwibe commented
@jakeherp 
Thanks for cheking. 
Thet's my mistake.
I will revert the formatting changes and request a merge.

Thank you!

2021-05-06 08:32 UTC, jakeherp approved these changes

2021-05-06 08:32 UTC, merged

2021-05-07 00:55 UTC, hubiwibe commented
@jakeherp 
Thank you so much!